name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Create .env file
        run: echo "$SECRET_ENV_CONTENT" > .env

      - name: Build Docker image
        run: docker build -t bookverse .
