# name: BookVerse CI/CD

# on:
#   push:
#     branches: ["master"]
#   pull_request:
#     branches: ["master"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: List files in the directory
#         run: ls -R

#       - name: Set up Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: 1.19

#       - name: Build and Run Docker
#         run: |
#           docker build -t bookverse .
#           docker run -p 8080:8080 bookverse
